# fly.toml app configuration file generated for siit on 2023-11-22T16:29:36-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "siit"
primary_region = "sin"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
