import baseSeo from './baseSeo';
import category from './category';
import blockContent from './blockContent';
import link from './link';
import site from './site';
import news from './news';
import event from './event';
import term from './term';
import banner from './banner';
export default [banner, link, news, baseSeo, term, category, blockContent, site, event];
